### PR TITLE
DATA-9299 Applying patch from opensource hive

### PR DESCRIPTION
**Pull request by s-pedamallu**
The bug is known in OSS - https://issues.apache.org/jira/browse/HIVE-11662
Picked and applied the patch as is: https://reviews.apache.org/r/38206/diff/

### CODE REVIEW

**Comment by s-pedamallu** [comment]
Test query:
```
SET hive.error.on.empty.partition=false;
SET hive.exec.compress.intermediate=true;
SET hive.exec.compress.output=true;
SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.max.dynamic.partitions = 1000000;
SET hive.exec.max.dynamic.partitions.pernode = 10000;
SET hive.exec.parallel=true;
SET hive.exec.parallel.thread.number=8;
SET hive.exec.reducers.bytes.per.reducer=8388608;
SET hive.exec.reducers.max=1000;
SET hive.execution.engine=tez;
SET hive.hadoop.supports.splittable.combineinputformat=true;
SET hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
SET hive.map.aggr=true;
SET hive.qubole.dynpart.use.prefix=true;
SET hive.support.quoted.identifiers=column;
SET hive.tez.auto.reducer.parallelism=true;
SET hive.vectorized.execution.enabled=true;
SET mapred.job.reuse.jvm.num.tasks=-1;
SET mapred.output.compress=true;
SET mapreduce.input.fileinputformat.split.maxsize=33554432;
SET mapreduce.input.fileinputformat.split.minsize=524288;
SET mapreduce.job.reduce.slowstart.completedmaps=0.5;
SET mapreduce.jobtracker.split.metainfo.maxsize=-1;
SET mapreduce.map.java.opts=-Xmx3600m;
SET mapreduce.map.memory.mb=4096;
SET mapreduce.map.output.compress=true;
SET mapreduce.map.output.compress.codec=org.apache.hadoop.io.compress.SnappyCodec;
SET mapreduce.reduce.java.opts=-Xmx3600m;
SET mapreduce.reduce.memory.mb=4096;
SET parquet.compression=SNAPPY;
SET tez.am.launch.cmd-opts=-Xmx3072m;
SET tez.am.resource.memory.mb=4096;
SET tez.grouping.max-size=33554432;
SET tez.grouping.min-size=524288;
SET tez.grouping.split-waves=1.2;
SET yarn.app.mapreduce.am.command-opts=-Xmx3072m;
SET yarn.app.mapreduce.am.resource.mb=4096;

INSERT OVERWRITE TABLE spedamallu.event_hive_query_logged_staging2 PARTITION(`ds`)
    SELECT
        event_id,
        MAX(CAST((
                    CASE WHEN `cluster` = 'true' THEN 'True'
                         WHEN `cluster` = 'false' THEN 'False'
                    ELSE `cluster` END
                ) AS STRING)) AS `cluster`,
        MAX(CAST((`cpu_time_secs`) AS BIGINT)) AS cpu_time_secs,
        IF((MAX(CAST((CASE WHEN (`created_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`created_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) = '', NULL, MAX(CAST((CASE WHEN (`created_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`created_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) AS created_at,
        IF((MAX(CAST((CASE WHEN (`ended_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`ended_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) = '', NULL, MAX(CAST((CASE WHEN (`ended_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`ended_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) AS ended_at,
        MAX(CAST((
                    CASE WHEN `environment` = 'true' THEN 'True'
                         WHEN `environment` = 'false' THEN 'False'
                    ELSE `environment` END
                ) AS STRING)) AS environment,
        MAX(CAST((
                    CASE WHEN `event_type` = 'true' THEN 'True'
                         WHEN `event_type` = 'false' THEN 'False'
                    ELSE `event_type` END
                ) AS STRING)) AS event_type,
        MAX(CAST((
                    CASE WHEN `execution_engine` = 'true' THEN 'True'
                         WHEN `execution_engine` = 'false' THEN 'False'
                    ELSE `execution_engine` END
                ) AS STRING)) AS execution_engine,
        MAX(CAST((
                    CASE WHEN `failure_info` = 'true' THEN 'True'
                         WHEN `failure_info` = 'false' THEN 'False'
                    ELSE `failure_info` END
                ) AS STRING)) AS failure_info,
        MAX(CAST((
                    CASE WHEN `http_request_id` = 'true' THEN 'True'
                         WHEN `http_request_id` = 'false' THEN 'False'
                    ELSE `http_request_id` END
                ) AS STRING)) AS http_request_id,
        MAX(CAST((`memory_bytes`) AS BIGINT)) AS memory_bytes,
        MAX(CAST((
                    CASE WHEN `metrics_json` = 'true' THEN 'True'
                         WHEN `metrics_json` = 'false' THEN 'False'
                    ELSE `metrics_json` END
                ) AS STRING)) AS metrics_json,
        IF((MAX(CAST((CASE WHEN (`occurred_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`occurred_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) = '', NULL, MAX(CAST((CASE WHEN (`occurred_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`occurred_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) AS occurred_at,
        MAX(CAST((
                    CASE WHEN `operation_name` = 'true' THEN 'True'
                         WHEN `operation_name` = 'false' THEN 'False'
                    ELSE `operation_name` END
                ) AS STRING)) AS operation_name,
        MAX(CAST((`port`) AS BIGINT)) AS port,
        MAX(CAST((
                    CASE WHEN `proxy_user` = 'true' THEN 'True'
                         WHEN `proxy_user` = 'false' THEN 'False'
                    ELSE `proxy_user` END
                ) AS STRING)) AS proxy_user,
        MAX(CAST((
                    CASE WHEN `query_id` = 'true' THEN 'True'
                         WHEN `query_id` = 'false' THEN 'False'
                    ELSE `query_id` END
                ) AS STRING)) AS query_id,
        MAX(CAST((
                    CASE WHEN `query_text` = 'true' THEN 'True'
                         WHEN `query_text` = 'false' THEN 'False'
                    ELSE `query_text` END
                ) AS STRING)) AS query_text,
        MAX(CAST((
                    CASE WHEN `reporter_hostname` = 'true' THEN 'True'
                         WHEN `reporter_hostname` = 'false' THEN 'False'
                    ELSE `reporter_hostname` END
                ) AS STRING)) AS reporter_hostname,
        MAX(CAST((
                    CASE WHEN `reporter_ip_address` = 'true' THEN 'True'
                         WHEN `reporter_ip_address` = 'false' THEN 'False'
                    ELSE `reporter_ip_address` END
                ) AS STRING)) AS reporter_ip_address,
        MAX(CAST((
                    CASE WHEN `server_address` = 'true' THEN 'True'
                         WHEN `server_address` = 'false' THEN 'False'
                    ELSE `server_address` END
                ) AS STRING)) AS server_address,
        MAX(CAST((
                    CASE WHEN `server_version` = 'true' THEN 'True'
                         WHEN `server_version` = 'false' THEN 'False'
                    ELSE `server_version` END
                ) AS STRING)) AS server_version,
        MAX(CAST((
                    CASE WHEN `session_id` = 'true' THEN 'True'
                         WHEN `session_id` = 'false' THEN 'False'
                    ELSE `session_id` END
                ) AS STRING)) AS session_id,
        MAX(CAST((
                    CASE WHEN `source_pipeline` = 'true' THEN 'True'
                         WHEN `source_pipeline` = 'false' THEN 'False'
                    ELSE `source_pipeline` END
                ) AS STRING)) AS source_pipeline,
        IF((MAX(CAST((CASE WHEN (`started_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`started_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) = '', NULL, MAX(CAST((CASE WHEN (`started_at` RLIKE "^[0-9]{4}-[0-9]{2}-[0-9]{2}([T ][0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+|)([\\+\\-][0-9]{2}:?[0-9]{2}|Z( [AaPp][Mm]|)|)|)$" ) THEN regexp_replace(regexp_replace(`started_at`, "T", " "), "([\\+\\-][0-9]{2}:?[0-9]{2}|[Zz])", "") END) AS TIMESTAMP))) AS started_at,
        MAX(CAST((
                    CASE WHEN `state` = 'true' THEN 'True'
                         WHEN `state` = 'false' THEN 'False'
                    ELSE `state` END
                ) AS STRING)) AS state,
        MAX(CAST((
                    CASE WHEN `submitted_method` = 'true' THEN 'True'
                         WHEN `submitted_method` = 'false' THEN 'False'
                    ELSE `submitted_method` END
                ) AS STRING)) AS submitted_method,
        MAX(CAST((
                    CASE WHEN `user` = 'true' THEN 'True'
                         WHEN `user` = 'false' THEN 'False'
                    ELSE `user` END
                ) AS STRING)) AS user_value,
        MAX(CAST(logged_at AS TIMESTAMP)) AS logged_at,
        MAX(ds) as ds
    FROM spedamallu.raw_staging_event_hive_query_logged
    WHERE ds>= '2019-12-01' AND ds<='2019-12-02'
    GROUP BY event_id;
```
Before applying patch:
```
2020-02-06T22:22:32,247 ERROR [dc992cae-01cd-46ba-bb52-3d30cbb414c8 main] exec.Task: Failed with exception Exception when loading 2 in table event_hive_query_logged_staging2 with loadPath=s3://lyftqubole-staging-iad/test/spedamallu/event_name=hive_query_logged_test/.hive-staging_hive_2020-02-06_21-57-31_898_1284779725873979389-1/-ext-10000
org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table event_hive_query_logged_staging2 with loadPath=s3://lyftqubole-staging-iad/test/spedamallu/event_name=hive_query_logged_test/.hive-staging_hive_2020-02-06_21-57-31_898_1284779725873979389-1/-ext-10000
        at org.apache.hadoop.hive.ql.metadata.Hive.loadDynamicPartitions(Hive.java:1963)
        at org.apache.hadoop.hive.ql.exec.MoveTask.execute(MoveTask.java:432)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:199)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
        at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2183)
        at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1839)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1526)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:233)
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:184)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:403)
        at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:821)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:759)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:686)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:244)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
Caused by: java.util.concurrent.ExecutionException: org.apache.hadoop.hive.ql.metadata.Table$ValidationFailureSemanticException: Partition spec {ds=2019-12-01, event_name=hive_query_logged_test} contains non-partition columns
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.hadoop.hive.ql.metadata.Hive.loadDynamicPartitions(Hive.java:1954)
        ... 20 more
Caused by: org.apache.hadoop.hive.ql.metadata.Table$ValidationFailureSemanticException: Partition spec {ds=2019-12-01, event_name=hive_query_logged_test} contains non-partition columns
        at org.apache.hadoop.hive.ql.metadata.Table.validatePartColumnNames(Table.java:384)
        at org.apache.hadoop.hive.ql.metadata.Hive.getPartition(Hive.java:2225)
        at org.apache.hadoop.hive.ql.metadata.Hive.getPartition(Hive.java:2181)
        at org.apache.hadoop.hive.ql.metadata.Hive.loadPartition(Hive.java:1611)
        at org.apache.hadoop.hive.ql.metadata.Hive$3.call(Hive.java:1922)
        at org.apache.hadoop.hive.ql.metadata.Hive$3.call(Hive.java:1913)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
After applying the patch:
```
Query ID = root_20200206222528_11b3b361-ed8e-4e39-a800-f98a861e3b56
Total jobs = 1
Launching Job 1 out of 1
Status: Running (Executing on YARN cluster with App id application_1581022925662_0001)

----------------------------------------------------------------------------------------------
        VERTICES      MODE        STATUS  TOTAL  COMPLETED  RUNNING  PENDING  FAILED  KILLED
----------------------------------------------------------------------------------------------
Map 1 .......... container     SUCCEEDED     23         23        0        0       0       0
Reducer 2 ...... container     SUCCEEDED    170        170        0        0       0       0
----------------------------------------------------------------------------------------------
VERTICES: 02/02  [==========================>>] 100%  ELAPSED TIME: 1599.42 s
----------------------------------------------------------------------------------------------
Loading data to table spedamallu.event_hive_query_logged_staging2 partition (ds=null)

Loaded : 2/2 partitions.
	 Time taken to load dynamic partitions: 39.871 seconds
	 Time taken for adding to write entity : 0.001 seconds
OK
Time taken: 1767.899 seconds
hive>
```

**Comment by s-pedamallu** [comment]
👀 @nanassito @rohit-menon

**Comment by s-pedamallu** [comment]
🚀

**Comment by nanassito** [comment]
Looks good. How did you test this ? (curious about how you got your version of hive running in a sonata cluster)

**Pull request merged**
